name: Test OpenAPI doc is valid on Pull Requests

on:
  pull_request:
    paths:
      - '.github/workflows/openapi-docs-pr.yml'
      - 'schemas/.spectral.yml'
      - "schemas/*/openapi.yml"

permissions:
  contents: read

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: schemas
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b
      - run: npm install
      - run: npm run lint:oas
